export const HERO = [
  {
    sketchLetter: "I",
    name: "Iron Man",
    brief: "Richest , Coolest and Smartest.",
    imgSrc1: "/marvimgs/IronMan/image1x1.png",
    imgSrc2: "/marvimgs/IronMan/image2x1.png",
    link: "iron",
    id :1,
    bg: "radial-gradient(circle at 60%,#7c0000 0%,#000000 100%)",
  },
  {
    sketchLetter: "H",
    name: "Hulk",
    brief: "Strongest and Short Tempered.",
    imgSrc1: "/marvimgs/Hulk/image1x1.png",
    imgSrc2: "/marvimgs/Hulk/image2x1.png",
    link: "hulk",
    id :2,
    bg: "radial-gradient(circle at 60%,#026302 0%,#000000 100%)",
  },
  {
    sketchLetter: "C",
    name: "Captain America",
    brief: "Leader and Fearless.",
    imgSrc1: "/marvimgs/Captain/image1x1.png",
    imgSrc2: "/marvimgs/Captain/image2x1.png",
    link: "captain",
    id :3,
    bg: "radial-gradient(circle at 60%,#021b6f 0%,#460204 70%,#000000 100%)",
  },
  {
    sketchLetter: "T",
    name: "Thor",
    brief: "God Of Thunder and Most Powerfull.",
    imgSrc1: "/marvimgs/Thor/image1x1.png",
    imgSrc2: "/marvimgs/Thor/image2x1.png",
    link: "thor",
    id :4,
    bg: "radial-gradient(circle at 60%,#e4eaec 0%,#040274 50%,#000000 100%)",
  },
  {
    sketchLetter: "b",
    name: "Black Widow",
    brief: "Warrior , Agent and Polite.",
    imgSrc1: "/marvimgs/Widow/image1x1.png",
    imgSrc2: "/marvimgs/Widow/image2x1.png",
    link: "widow",
    id :5,
    bg: "radial-gradient(circle at 60%,#ffffff 0%,#000000 100%)",
  },
  {
    sketchLetter: "h",
    name: "Hawkeye",
    brief: "Archer, Quickest and Focused.",
    imgSrc1: "/marvimgs/Hawk/image1x1.png",
    imgSrc2: "/marvimgs/Hawk/image2x1.png",
    link: "hawk",
    id :6,
    bg: " radial-gradient(circle at 60%,#500e0e 0%,#000000 100%)",
  },
];

export const LANDING_HEROES = [
  {
    name: "iron",
    topImg: "/marvimgs/IronMan/8689406.jpg",
    letter: "I",
    bottomImg: "/marvimgs/IronMan/IronSuits.jpg",
    bg: "radial-gradient(circle at 60%,#7c0000 0%,#000000 100%)",
    headColor: "#ff0000",
    shadowColor: "#ffffff",
  },
  {
    name: "hulk",
    topImg: "/marvimgs/Hulk/HulkGamma.jpg",
    letter: "H",
    bottomImg: "/marvimgs/Hulk/RagnHulk.jpg",
    bg: "radial-gradient(circle at center,rgb(14, 177, 14) 0%,black 100%)",
    headColor: "#adff2f",
    shadowColor: "#808080",
  },
  {
    name: "thor",
    topImg: "/marvimgs/Thor/thorlight.jpg",
    letter: "T",
    bottomImg: "/marvimgs/Thor/thorMjolnir.jpg",
    bg: "radial-gradient(circle at center,rgb(40, 149, 245) 0%,black 100%)",
    headColor: "#0000ff",
    shadowColor: "#ffffff",
  },
  {
    name: "widow",
    topImg: "/marvimgs/Widow/widow.jpeg",
    letter: "b",
    bottomImg: "/marvimgs/Widow/BlackWidow.jpg",
    bg: "radial-gradient(circle at center,rgba(255, 255, 255, 0.58) 0%,rgb(255, 0, 0) 50%,black 80%,black 100%)",
    headColor: "#2c2929",
    shadowColor: "#808080",
  },
  {
    name: "hawk",
    topImg: "/marvimgs/Hawk/hakw.jpg",
    letter: "h",
    bottomImg: "/marvimgs/Hawk/Hawk.png",
    bg: "radial-gradient(circle at center,rgb(0, 0, 0) 0%,black 100%)",
    headColor: "#ffffff",
    shadowColor: "#000000",
  },
  {
    name: "captain",
    topImg: "/marvimgs/Captain/captain.jpg",
    letter: "C",
    bottomImg: "/marvimgs/Captain/Captain2.jpg",
    bg: "radial-gradient(circle at center,rgb(14, 15, 76) 0%,black 100%)",
    headColor: "#0000ff",
    shadowColor: "#ffffff",
  },
];